"""add answers like

Revision ID: 3d71ffbb0244
Revises: 051e48bf356b
Create Date: 2025-12-20 18:16:13.679835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d71ffbb0244'
down_revision: Union[str, Sequence[str], None] = '051e48bf356b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('answers', sa.Column('dislike_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_answers_grade_count'), table_name='answers')
    op.drop_column('answers', 'grade_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('grade_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_answers_grade_count'), 'answers', ['grade_count'], unique=False)
    op.drop_column('answers', 'dislike_count')
    op.drop_column('answers', 'like_count')
    # ### end Alembic commands ###
