"""add dislike count and like count

Revision ID: 8e590272304e
Revises: ec47f400dd78
Create Date: 2025-12-19 01:18:40.764720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e590272304e'
down_revision: Union[str, Sequence[str], None] = 'ec47f400dd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('questions', sa.Column('dislike_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('indx_grade_count_desc'), table_name='questions')
    op.create_index('indx_grade_count_desc', 'questions', [sa.literal_column('like_count DESC')], unique=False)
    op.drop_column('questions', 'grade_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('grade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index('indx_grade_count_desc', table_name='questions')
    op.create_index(op.f('indx_grade_count_desc'), 'questions', [sa.literal_column('grade_count DESC')], unique=False)
    op.drop_column('questions', 'dislike_count')
    op.drop_column('questions', 'like_count')
    # ### end Alembic commands ###
