"""add ts search

Revision ID: 9545963c7920
Revises: f25730346ac7
Create Date: 2025-12-25 01:36:50.801104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9545963c7920'
down_revision: Union[str, Sequence[str], None] = 'f25730346ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title,'')), 'A') || setweight(to_tsvector('russian', coalesce(text,'')),  'B')", persisted=True), nullable=False))
    op.create_index('ix_question_search_vector', 'questions', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_search_vector', table_name='questions', postgresql_using='gin')
    op.drop_column('questions', 'search_vector')
    # ### end Alembic commands ###
