"""add grade

Revision ID: ec47f400dd78
Revises: 
Create Date: 2025-12-17 23:06:58.570106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec47f400dd78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_grade',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_index(op.f('ix_question_grade_created_at'), 'question_grade', ['created_at'], unique=False)
    op.create_table('answer_grade',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'answer_id')
    )
    op.create_index(op.f('ix_answer_grade_created_at'), 'answer_grade', ['created_at'], unique=False)
    op.drop_index(op.f('ix_answer_likes_created_at'), table_name='answer_likes')
    op.drop_table('answer_likes')
    op.drop_index(op.f('ix_question_likes_created_at'), table_name='question_likes')
    op.drop_table('question_likes')
    op.add_column('answers', sa.Column('grade_count', sa.BigInteger(), server_default="0", nullable=False))
    op.drop_index(op.f('ix_answers_likes_count'), table_name='answers')
    op.create_index(op.f('ix_answers_grade_count'), 'answers', ['grade_count'], unique=False)
    op.drop_column('answers', 'likes_count')
    op.add_column('questions', sa.Column('grade_count', sa.Integer(), nullable=False,  server_default="0"))
    op.drop_index(op.f('indx_likes_count_desc'), table_name='questions')
    op.create_index('indx_grade_count_desc', 'questions', [sa.literal_column('grade_count DESC')], unique=False)
    op.drop_column('questions', 'likes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('indx_grade_count_desc', table_name='questions')
    op.create_index(op.f('indx_likes_count_desc'), 'questions', [sa.literal_column('likes_count DESC')], unique=False)
    op.drop_column('questions', 'grade_count')
    op.add_column('answers', sa.Column('likes_count', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_answers_grade_count'), table_name='answers')
    op.create_index(op.f('ix_answers_likes_count'), 'answers', ['likes_count'], unique=False)
    op.drop_column('answers', 'grade_count')
    op.create_table('question_likes',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('question_likes_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('question_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name=op.f('question_likes_pkey'))
    )
    op.create_index(op.f('ix_question_likes_created_at'), 'question_likes', ['created_at'], unique=False)
    op.create_table('answer_likes',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('answer_likes_answer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('answer_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name=op.f('answer_likes_pkey'))
    )
    op.create_index(op.f('ix_answer_likes_created_at'), 'answer_likes', ['created_at'], unique=False)
    op.drop_index(op.f('ix_answer_grade_created_at'), table_name='answer_grade')
    op.drop_table('answer_grade')
    op.drop_index(op.f('ix_question_grade_created_at'), table_name='question_grade')
    op.drop_table('question_grade')
    # ### end Alembic commands ###
