"""add answer likes

Revision ID: f25730346ac7
Revises: 3d71ffbb0244
Create Date: 2025-12-20 21:13:18.834069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25730346ac7'
down_revision: Union[str, Sequence[str], None] = '3d71ffbb0244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_grade', sa.Column('is_like', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_grade', 'is_like')
    # ### end Alembic commands ###
